
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: hermes_test
      - image: redis
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle cache
      - restore_cache:
          keys:
            - chaskiq-bundle-v2-{{ checksum "Gemfile.lock" }}
            - chaskiq-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: chaskiq-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - chaskiq-yarn-{{ checksum "yarn.lock" }}
            - chaskiq-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      # Store yarn / webpacker cache
      - save_cache:
          key: chaskiq-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - type: shell
        command: |
          bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - type: shell
        command: |
          yarn cypress run



workflows:
  build:
    jobs:
      - cypress/run:
          # install Ruby dependencies
          build: bundle install
          start: ls && rails server
          wait-on: 'http://localhost:5002'
          executor: with-ruby
          no-workspace: true