development:
  #adapter: async
  #adapter: redis
  adapter: <%= ENV.fetch("CABLE_ADAPTER") { 'redis' } %>

test:
  adapter: async

production:
  #adapter: any_cable
  #adapter: redis
  adapter: <%= ENV.fetch("CABLE_ADAPTER") { 'redis' } %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: hermes_production
