subscriptions:
  plans:
    - 
      name: "free"
      description: Este es el plan gratuito!
      id: 618560
      features:
        -
          name: Segments
          active: true
          count: unlimited
        -
          name: Leads
          active: true
          count: unlimited
        -
          name: AppUsers
          active: true
          count: unlimited
        - 
          name: Conversations
          active: true
          count: unlimited

        - 
          name: BotTasks
          active: true
          count: unlimited
        - 
          name: Integrations
          active: true
          count: unlimited

        - 
          name: Campaigns
          active: false
          count: unlimited

        - 
          name: Tours
          active: true
          count: unlimited

        - 
          name: UserAutoMessages
          active: true
          count: unlimited

        - name: OutgoingWebhooks
          active: false
          count: unlimited

        - name: OauthApplications
          active: true
          count: unlimited
          
        - name: Articles
          active: false
          count: unlimited

        - name: QuickReplies
          active: true
          count: unlimited

        - name: CustomAttributes
          active: true
          count: unlimited

    - 
      name: "rookie"
      description: Este es el plan simple
      id: 616249
      features:
        -
          name: Segmentos
        - 
          name: Conversaciones
        - 
          name: Campañas 
        - 
          name: Flujos de Chat
        - 
          name: Integraciones API
    - 
      name: "super"
      id: 596123
      description: Este es el super plan
      features:
        -
          name: Segmentos
        - 
          name: Conversaciones
        - 
          name: Campañas 
        - 
          name: Flujos de Chat
        - 
          name: Integraciones API