# .github/workflows/ci.yml

name: CI
on: [push] #, pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
 

      #- name: Build and run tests
      #  env:
      #    DATABASE_URL: postgres://postgres:@localhost:5432/test
      #    REDIS_URL: redis://localhost:6379/0
      #    RAILS_ENV: test
      #    RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      #  run: |
      #    sudo apt-get -yqq install libpq-dev
      #    gem install bundler
      #    bundle install --jobs 4 --retry 3
      #    bundle exec rails db:prepare
      #    bundle exec rspec ./spec

      - name: Build and run E2E tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare

          cp ./config/webpacker.ci.yml ./config/webpacker.yml
          bundle exec rails server -e test -p 5002 -d
          bundle exec rake assets:precompile
          ./node_modules/.bin/cypress install
          yarn cypress run
          #bundle exec rake assets:precompile
          #bundle exec rspec ./spec/system  -t browser


      #- name: Run migrations
      #  run: bin/rubocop

      #- name: Run Rubocop
      #  run: bin/rubocop
      #- name: Run Style Lint
      #  run: bin/stylelint
      #- name: Run Prettier
      #  run: bin/prettier
      #- name: Run ESLint
      #  run: bin/eslint

      #- name: Run Bundler Audit
      #  run: bin/bundler-audit --update
      #- name: Run Brakeman
      #  run: bin/brakeman -q -w2


      #- name: Run tests
      #  run: bin/rspec